### ISSUE TITLE
Relay node file size limit or bandwidth limit?

### ISSUE THREAD

**Issue by trymeouteh** [LeastAuthority/destiny#240]
Is there a file size limit or bandwidth limitations when sharing files through a relay node?

**Comment by meejah** [comment]
Transit relays could impose any limits they like, but "in general" clients should conduct themselves reasonably. There's nothing built in to the protocol to limit sizes.

**Comment by meejah** [comment]
(Since you opened several issues as questions, can I ask if you looked for but didn't find other ways to ask these questions? Perhaps this bug should be re-opened and turned into a request for that information?)

**Comment by trymeouteh** [comment]
I do not understand what you mean by "clients should conduct themselves reasonably"

I did not mean to open a bug issue to ask questions. Could you perhaps add a discussions tab to this github repo. Discussions tabs creates a forum section where other github users can post feature requests, ask questions, have discussions, etc which will remain separate from the issue tracker. Not many github repos use the discussion feature I find :(

**Comment by meejah** [comment]
> I do not understand what you mean by "clients should conduct themselves reasonably"

I just mean we haven't so far needed to do much blocking etc. as far as I know.
